Zadanie: Wyszukujemy pracowników o podanych nazwiskach oraz firmy...
woitech/wojciech-lowczecki-kodilla-java pull request #31
Opened 2018-02-06 00:52 UTC by woitech

2018-02-06 20:37 UTC, aszecowka requested changes

2018-02-06 20:37 UTC, aszecowka commented on kodilla-hibernate/src/test/java/com/kodilla/hibernate/manytomany/dao/CompanyDaoTestSuite.java
> +    // chyba pachnie trochę lenistwem i zazdrością?
nice :)

2018-02-06 20:37 UTC, aszecowka commented on kodilla-hibernate/src/main/java/com/kodilla/hibernate/manytomany/Company.java
> +        query = "SELECT * FROM COMPANIES WHERE :PREFIX LIKE '_%' AND COMPANY_NAME LIKE CONCAT(:PREFIX, '%') ORDER BY COMPANY_NAME",
I don't undesrtand first condition: :PREFIX LIKE '_%', could you explain me it?
Another option was to use SUBSTRING method

2018-02-07 15:31 UTC, woitech commented on kodilla-hibernate/src/main/java/com/kodilla/hibernate/manytomany/Company.java
> +        query = "SELECT * FROM COMPANIES WHERE :PREFIX LIKE '_%' AND COMPANY_NAME LIKE CONCAT(:PREFIX, '%') ORDER BY COMPANY_NAME",
You're right you don't understand, condition WHERE string LIKE '_%' is wrong. Every string starts with empty string because concat('', 'abc') = 'abc'

2018-02-07 15:38 UTC, woitech commented on kodilla-hibernate/src/test/java/com/kodilla/hibernate/manytomany/dao/CompanyDaoTestSuite.java
> +    // chyba pachnie trochę lenistwem i zazdrością?
I think Company could have addEmployee(Employee employee) {
    this.employees.add(employee);
    employee.getCompanies.add(this);
}
What do you think?

2018-02-07 15:42 UTC, woitech commented on kodilla-hibernate/src/main/java/com/kodilla/hibernate/manytomany/Company.java
> +        query = "SELECT * FROM COMPANIES WHERE :PREFIX LIKE '_%' AND COMPANY_NAME LIKE CONCAT(:PREFIX, '%') ORDER BY COMPANY_NAME",
... so retrieveCompaniesWithNamePrefix("") should be equivalent for findAll()

2018-02-09 12:08 UTC, aszecowka approved these changes

2018-02-25 00:06 UTC, closed without merging